// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Tx-DRKa_t6g7FOLoqXo6o7ztn9aNo9Y',
    appId: '1:63727632365:web:3bd6541536199433c271e4',
    messagingSenderId: '63727632365',
    projectId: 'app-dev-final-3fd2c',
    authDomain: 'app-dev-final-3fd2c.firebaseapp.com',
    storageBucket: 'app-dev-final-3fd2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvIs0snMSNo8CwrlfRPlnkjrYVRz1nEE',
    appId: '1:63727632365:android:7c58a8511d4aadb3c271e4',
    messagingSenderId: '63727632365',
    projectId: 'app-dev-final-3fd2c',
    storageBucket: 'app-dev-final-3fd2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9me5N9Xq-LYBZjKdZ0m_w95VjgaQFe5Y',
    appId: '1:63727632365:ios:be2052b65b186901c271e4',
    messagingSenderId: '63727632365',
    projectId: 'app-dev-final-3fd2c',
    storageBucket: 'app-dev-final-3fd2c.appspot.com',
    iosBundleId: 'com.example.appDevFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9me5N9Xq-LYBZjKdZ0m_w95VjgaQFe5Y',
    appId: '1:63727632365:ios:0c8f476aa7b78cb8c271e4',
    messagingSenderId: '63727632365',
    projectId: 'app-dev-final-3fd2c',
    storageBucket: 'app-dev-final-3fd2c.appspot.com',
    iosBundleId: 'com.example.appDevFinal.RunnerTests',
  );
}
